config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root to: "Welcome#index"
  resources :companies do
    member do
      get :home
    end
    member do
      get :all_events
    end
    scope module:'company' do
      resources :jobs, controller: 'job_opportunities' do
        patch :select_candidates
        member do
          post 'select_candidates/mail' => :send_mail_to_all_shortlisted_candidates
          post 'select_candidate/:candidate_id/mail' => :send_mail_to_shortlisted_candidate, as: 'send_mail_to_candidate'
        end
        resources :events, controller: 'events'
      end
    end
  end

  resources :admins

  resources :candidates do
    member do
      get 'home'
      get 'resume'
      get 'jobs'
      scope 'jobs' do
        post ':job_id/apply' => :apply_job, as:'apply_job'
      end
    end
    scope module:'candidate' do
      resources :achievements, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources :projects, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources :course_scores
      resources :experiences, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources  :links, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources :references, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
    end
  end

  scope '/candidates/:candidate_id/' do
    resources :qualifications, as:'candidate_qualification', except:[:edit,:show,:new] do
      collection do
        get 'edit'
      end
    end
    resources :skills, as:'candidate_skill', except:[:edit,:show,:new,:update,:create,:destroy] do
      collection do
        get 'edit',as: 'edit'
        put 'update',as: 'update'
      end
    end
    resource :location , as:'candidate_location'
  end

  scope '/companies/:company_id/' do
    resource :location, as:'company_location'
    resources :reviews, as:'company_reviews', only:[:index,:show]
    scope 'jobs/:job_id' do
      resources :qualifications, as:'job_qualification'
      resources :skills, as:'job_skill'
      scope '/events/:event_id' do
        resource :location, as: 'event_location'
      end
    end
  end

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Listing Admins</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
    <tr>
      <td><%= link_to 'Show', admin %></td>
      <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
      <td><%= link_to 'Destroy', admin #method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<%= link_to 'Edit', edit_admin_path(@admin) %>
|
<%= link_to 'Back', admins_path %>