config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root to: "Welcome#index"
  resources :companies do
    member do
      get :home
    end
    member do
      get :all_events
    end
    scope module:'company' do
      resources :jobs, controller: 'job_opportunities' do
        patch :select_candidates
        member do
          post 'select_candidates/mail' => :send_mail_to_all_shortlisted_candidates
          post 'select_candidate/:candidate_id/mail' => :send_mail_to_shortlisted_candidate, as: 'send_mail_to_candidate'
        end
        resources :events, controller: 'events'
      end
    end
  end

  resources :admins

  resources :candidates do
    member do
      get 'home'
      get 'resume'
      get 'jobs'
      scope 'jobs' do
        post ':job_id/apply' => :apply_job, as:'apply_job'
      end
    end
    scope module:'candidate' do
      resources :achievements, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources :projects, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources :course_scores
      resources :experiences, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources  :links, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources :references, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
    end
  end

  scope '/candidates/:candidate_id/' do
    resources :qualifications, as:'candidate_qualification', except:[:edit,:show,:new] do
      collection do
        get 'edit'
      end
    end
    resources :skills, as:'candidate_skill', except:[:edit,:show,:new,:update,:create,:destroy] do
      collection do
        get 'edit',as: 'edit'
        put 'update',as: 'update'
      end
    end
    resource :location , as:'candidate_location'
  end

  scope '/companies/:company_id/' do
    resource :location, as:'company_location'
    resources :reviews, as:'company_reviews', only:[:index,:show]
    scope 'jobs/:job_id' do
      resources :qualifications, as:'job_qualification'
      resources :skills, as:'job_skill'
      scope '/events/:event_id' do
        resource :location, as: 'event_location'
      end
    end
  end

end

app/models/candidate/qualification/course_score.rb
class Candidate::Qualification::CourseScore < ActiveRecord::Base

  self.table_name = 'candidate_qualification_course_scores'

  include DatabaseStorageFormat
  
  before_save :lower_fields

	belongs_to :qualification

	validates :course, :presence => true, length: { maximum: 255 }
	validates :end_year, :presence => true
	validates :score, :presence => true, :numericality => {:greater_than => 0, :less_than => 100}

  validates_associated :qualification
end

app/models/qualification.rb
class Qualification
include Mongoid::Document
  # concerns
	include DatabaseStorageFormat

  # callbacks
  before_save :lower_fields

  # relationships
	has_many :course_scores,class_name: 'Candidate::CourseScore'
  has_many :qualification_assignments


  # validations
	validates :course, :presence => true, :length => { maximum: 255 }
	validates :domain, :presence => true, :length => { maximum: 255 }

end

app/controllers/qualifications_controller.rb
class QualificationsController < ApplicationController

  # helpers
  include QualificationsHelper

  #layout
  layout 'candidate/layout'


  # filter/callbacks
  before_action :set_entity

  # GET */qualifications
  # GET */qualifications.json
  def index
    authorize! :index, @entity
    if @entity.class == Company::JobOpportunity
      @qualifications = @entity.qualifications
    else 
      @entity_institutes_with_qualifications = @entity.get_institutes_with_qualifications
    end
  end

  # GET */qualifications/1/edit
  def edit
    authorize! :edit, @entity 
    if @entity.class == Company::JobOpportunity
      @entity_qualifications = @entity.qualifications
      @new_entity_qualification = Qualification.new
      render :edit_job
    elsif @entity.class == Candidate
      @entity_institutes_with_qualifications = @entity.get_institutes_with_qualifications
      @new_entity_institute = Institute.new
      @new_entity_qualification = Qualification.new
      render :edit_candidate
    end
  end

  # POST */qualifications
  # POST */qualifications.json
  def create
    authorize! :create, @entity
    if @entity.class == Candidate
      @institute = Institute.find_or_create_by(institute_params)
      @qualification = Qualification.find_or_create_by(qualification_params)
      if @institute.id && @qualification.id && @entity.add_institute_with_qualification(@institute,@qualification)
        flash[:success] = 'Qualification was successfully created'
        redirect_to edit_candidate_qualification_index_path(candidate_id:params[:candidate_id])
      else
        flash[:failure] = 'Qualification creation unsuccessful'
        redirect_to edit_candidate_qualification_index_path(candidate_id:params[:candidate_id])
      end
    elsif @entity.class == Comapany::JobOpportunity
      @qualification = Qualification.new(qualification_params)

      respond_to do |format|
        if @qualification.save
          @entity.qualifications << @qualification
          flash[:notice] = 'Qualification was successfully created.'
          format.html { redirect_to self.send(qualification_path,qualification_path_params(@qualification)) }
          format.json { render :show, status: :created, location: @qualification }
        else
          format.html { render :new }
          format.json { render json: @qualification.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT */qualifications/1
  # PATCH/PUT */qualifications/1.json
  def update
    authorize! :update, @entity
    if @entity.class == Candidate
      @institute = Institute.find_or_create_by(institute_params)
      @qualification = Qualification.find_or_create_by(qualification_params)
      if @institute.id && @qualification.id && @entity.update_institute_with_qualification(@institute,@qualification,params[:candidate_id],params[:id])
        flash[:success] = 'Qualification successfully updated'
        redirect_to edit_candidate_qualification_index_path(candidate_id:params[:candidate_id])
      else
        flash[:failure] = 'Qualification updation unsuccessful'
        redirect_to edit_candidate_qualification_index_path(candidate_id:params[:candidate_id])
      end
    elsif @entity.class == Company::JobOpportunity
      respond_to do |format|
        if @qualification.update(qualification_params)
          flash[:notice] = 'Qualification was successfully updated.'
          format.html { redirect_to self.send(qualification_path,qualification_path_params(@qualification)) }
          format.json { render :show, status: :ok, location: @qualification }
        else
          format.html { render :edit }
          format.json { render json: @qualification.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE */qualifications/1
  # DELETE */qualifications/1.json
  def destroy
    if @entity.class == Candidate
      authorize! :destroy, @entity
      cqa = CandidateQualificationAssignment.find_by(candidate_id: params[:candidate_id],qualification_assignment_id:params[:id])
      if cqa.destroy
        flash[:success] = 'Qualification successfully deleted'
        redirect_to edit_candidate_qualification_index_path(candidate_id:params[:candidate_id])
      end
    elsif @entity.class == Company::JobOpportunity
      @entity.qualifications.destroy(@qualification)
      flash[:notice] = 'Qualification was successfully destroyed.'
      respond_to do |format|
        format.html { redirect_to self.send(qualification_path('index')) }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      if params.has_key?(:candidate_id)
        @entity = Candidate.find(params[:candidate_id])
      elsif params.has_key?(:job_id)
        @entity = Company::JobOpportunity.find(params[:job_id])
      end
    end

    def set_qualification
      @qualification = @entity.qualifications.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qualification_params
      params.require(:qualification).permit(:course,:domain)
    end

    def institute_params
      params.require(:institute).permit(:university,:campus)
    end
end

app/helpers/qualifications_helper.rb
module QualificationsHelper

  # Return qualification path of candidate or job as string
  def qualification_path(*prefix_or_suffix)
    prefix_or_suffix = prefix_or_suffix[0] if prefix_or_suffix.length == 1
    path = @entity.instance_of?(Candidate) ? 'candidate_qualification' : 'job_qualification'
    path = prefix_or_suffix.nil? ? path : (prefix_or_suffix == 'index') ? path+'_'+prefix_or_suffix : prefix_or_suffix+'_'+path
    path+'_path'
  end

  # Return qualification path params which accepts an object
  def qualification_path_params(qualification)
    id = qualification.id
    @entity.instance_of?(Candidate) ? {candidate_id: params[:candidate_id],id: id} : {company_id: params[:company_id],job_id: params[:job_id],id: id}
  end

end

app/views/qualifications/_form.html.erb
<div class="row">
  <div class="col-sm-9">
    <%= form_for entity_qualification, url: required_url do |f| %>
      <% if entity_qualification.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(entity_qualification.errors.count, "error") %> prohibited this qualification from being saved:</h2>

          <ul>
          <% entity_qualification.errors.full_messages.each do |message| %>
            <li><%# message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>


      <div class="form-group">
        <%= f.label(:course, class: "control-label col-sm-3")  %>
        <div class="col-sm-9">
          <%= f.text_field(:course, class: "form-control",placeholder:"Enter course") %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label(:domain, class: "control-label col-sm-3")  %>
        <div class="col-sm-9">
          <%= f.text_field(:domain, class: "form-control",placeholder:"Enter domain") %>
        </div>
      </div>
  </div>

  <div class="form-group">
    <% if !new_qualification %>
      <div class="col-sm-2">
        <%= f.submit "Update",class: "btn btn-default update-button btn-md" %>
      </div>
    <% else %>
      <div class="col-sm-offset-2 create-button">
        <%= f.submit "Create",class:"btn btn-default" %>
      </div>
    <% end %>
  </div>
<% end %>
<% if !new_qualification %>
  <div class="form-group">
    <div class="col-sm-1">
      <%= link_to "Delete",candidate_qualification_path(candidate_id:params[:candidate_id],id:entity_qualification.id),method: :delete, class:"btn btn-danger btn-md active", role:"button" %>

    </div>
  </div>
<% end %>
</div>

app/views/qualifications/_form_2.html.erb
<div class="row well">
  <div class="col-sm-9">
    <%= form_for entity_institute, url: required_url do |f| %>
      <% if entity_institute.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(entity_institute.errors.count, "error") %> prohibited this qualification from being saved:</h2>

          <ul>
          <% entity_institute.errors.full_messages.each do |message| %>
            <li><%# message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>


      <div class="form-group">
        <%= f.label(:university, class: "control-label col-sm-3")  %>
        <div class="col-sm-9">
          <%= f.text_field(:university, class: "form-control",placeholder:"Enter university") %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label(:campus, class: "control-label col-sm-3")  %>
        <div class="col-sm-9">
          <%= f.text_field(:campus, class: "form-control",placeholder:"Enter campus") %>
        </div>
      </div>

      <%= fields_for entity_qualification do |qual| %> 
        <div class="form-group">
          <%= qual.label(:course, class: "control-label col-sm-3")  %>
          <div class="col-sm-9">
            <%= qual.text_field(:course, class: "form-control",placeholder:"Enter course") %>
          </div>
        </div>
        <div class="form-group">
          <%= qual.label(:domain, class: "control-label col-sm-3")  %>
          <div class="col-sm-9">
            <%= qual.text_field(:domain, class: "form-control",placeholder:"Enter domain") %>
          </div>
        </div>
      <% end %>
  </div>

  <div class="form-group">
    <% if !new_qualification %>
      <div class="col-sm-2">
        <%= f.submit "Update",class: "btn btn-default update-button btn-md" %>
      </div>
    <% else %>
      <div class="col-sm-offset-2 create-button">
        <%= f.submit "Create",class:"btn btn-default" %>
      </div>
    <% end %>
  </div>
<% end %>
<% if !new_qualification %>
  <div class="form-group">
    <div class="col-sm-1">
      <%= link_to "Delete",required_url,method: :delete, class:"btn btn-danger btn-md active", role:"button" %>

    </div>
  </div>
<% end %>
</div>

app/views/qualifications/edit_candidate.html.erb
<% content_for :edit_content do %>
  <div class="row qualification-title">
    <h2 class="col-sm-5">Qualifications</h2>

    <button class="btn btn-default col-sm-1 add-button-qualification" data-toggle="modal" data-target="#myModal"> Add</button>
  </div>
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add qualification</h4>
        </div>
        <div class="modal-body">
          <%= render partial: 'form_2', locals:{entity_institute: @new_entity_institute,entity_qualification:@new_entity_qualification,required_url:candidate_qualification_index_path,new_qualification: true} %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
  <% @entity_institutes_with_qualifications.each do |entity| %>
    <%= render partial: 'form_2',locals:{entity_institute: entity[:institute],entity_qualification: entity[:qualification] ,required_url:candidate_qualification_path(candidate_id:params[:candidate_id],id:entity[:qual_ass_id]),new_qualification: false} %>
  <% end %>
<% end %>

<%= render 'candidates/edit_navbar' %>

app/views/qualifications/edit_job.html.erb
<% content_for :edit_content do %>
  <div class="row qualification-title">
    <h2 class="col-sm-5">Qualifications</h2>
    <button class="btn btn-default col-sm-1 add-button-qualification" data-toggle="modal" data-target="#myModal"> Add</button>
  </div>
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add qualification</h4>
        </div>
        <div class="modal-body">
          <%= render partial: 'form', locals:{entity_qualification: @new_entity_qualification,required_url:candidate_qualification_index_path,new_qualification: true} %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

  <% @entity_qualifications.each do |entity_qualification| %>
    <%= render partial: 'form',locals:{ entity_qualification: entity_qualification ,required_url: candidate_qualification_path(candidate_id:params[:candidate_id],id:entity_qualification.id),new_qualification: false} %>
  <% end %>
<% end %>

<%= render 'candidates/edit_navbar' %>

app/views/qualifications/index.html.erb
<% content_for :show_content do %>
  <h2>Qualifications</h2>
  <% @entity_institutes_with_qualifications.each do |entity| %>
    <div class="well">
      <div class="row">
        <div class="col-sm-3">
          <p><b>Course</b></p>
        </div>
        <div class="col-sm-9">
          <p><%= entity[:qualification].course %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <p><b>Domain</b></p>
        </div>
        <div class="col-sm-9">
          <p><%= entity[:qualification].domain %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <p><b>Campus</b></p>
        </div>
        <div class="col-sm-9">
          <p><%= entity[:institute].campus %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <p><b>University</b></p>
        </div>
        <div class="col-sm-9">
          <p><%= entity[:institute].university  %></p>
        </div>
      </div>
    </div>
  <% end %> 
  <%= link_to "Edit qualifications",edit_candidate_qualification_index_path(params[:id]||params[:candidate_id]),class:"btn btn-default",onclick:"javascript:window.location.reload()" %>
<% end %>
<%= render "candidates/show_navbar" %>