config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root to: "Welcome#index"
  resources :companies do
    member do
      get :home
    end
    member do
      get :all_events
    end
    scope module:'company' do
      resources :jobs, controller: 'job_opportunities' do
        patch :select_candidates
        member do
          post 'select_candidates/mail' => :send_mail_to_all_shortlisted_candidates
          post 'select_candidate/:candidate_id/mail' => :send_mail_to_shortlisted_candidate, as: 'send_mail_to_candidate'
        end
        resources :events, controller: 'events'
      end
    end
  end

  resources :admins

  resources :candidates do
    member do
      get 'home'
      get 'resume'
      get 'jobs'
      scope 'jobs' do
        post ':job_id/apply' => :apply_job, as:'apply_job'
      end
    end
    scope module:'candidate' do
      resources :achievements, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources :projects, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources :course_scores
      resources :experiences, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources  :links, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources :references, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
    end
  end

  scope '/candidates/:candidate_id/' do
    resources :qualifications, as:'candidate_qualification', except:[:edit,:show,:new] do
      collection do
        get 'edit'
      end
    end
    resources :skills, as:'candidate_skill', except:[:edit,:show,:new,:update,:create,:destroy] do
      collection do
        get 'edit',as: 'edit'
        put 'update',as: 'update'
      end
    end
    resource :location , as:'candidate_location'
  end

  scope '/companies/:company_id/' do
    resource :location, as:'company_location'
    resources :reviews, as:'company_reviews', only:[:index,:show]
    scope 'jobs/:job_id' do
      resources :qualifications, as:'job_qualification'
      resources :skills, as:'job_skill'
      scope '/events/:event_id' do
        resource :location, as: 'event_location'
      end
    end
  end

end

app/models/company.rb
class Company
include Mongoid::Document
  # concerns
  include ForbiddenValues
  include DatabaseStorageFormat

  # callbacks
  before_save :lower_fields
  

  # associations
  has_many :job_opportunities, dependent: :destroy
  has_many :events, through: :job_opportunities
  has_one :location, as: :locatable, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :user

  # validations
  
  mount_uploader :logo, LogoUploader
  validates :name, presence:true, length: { :maximum => 255 }
  validates :company_type, presence:true, length: { :maximum => 255 }
  validates :description, presence:true
  validates :url, presence:true, length: { :maximum => 255 }

  def recent_events(event_count=5)
    self.events.order("created_at DESC").limit(event_count)
  end

end

app/models/company/event.rb
class Company::Event
include Mongoid::Document
  # concerns
  include ForbiddenValues
  include DatabaseStorageFormat

  #scopes
  # scope :sorted_events, lambda { order("created_at ")}

  # callbacks
  before_save :lower_fields

  # TODO
  # after_create :send_email_to_candidates

  # associations
  belongs_to :job_opportunity
  has_one :location, as: :locatable
  accepts_nested_attributes_for :location

  # validations
  validates :event_type, presence:true, :format => REGEX_NAME_FORMAT, length: { :maximum => 255}
  validates :date_time, presence:true
  validates :duration, presence:true

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  #Helper
  include Company::JobOpportunitiesHelper

  #cancan
  load_and_authorize_resource

  # callbacks

  # GET /companies
  # GET /companies.json
  def index
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end


  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.user_id = current_user.id
    respond_to do |format|
      if @company.save
        flash[:notice] = 'Company was successfully created.'
        format.html { redirect_to new_company_job_path(@company) }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        flash[:success] = 'Company was successfully updated.'
        format.html { redirect_to home_company_path(@company) }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      flash[:success] = 'Company was successfully destroyed.'
      format.html { redirect_to companies_url}
      format.json { head :no_content }
    end
  end


  def home
    @jobs = @company.job_opportunities.paginate(:page => params[:page],:per_page => 10)
    if @company.job_opportunities.empty?
      redirect_to new_company_job_path(@company)
    end
  end

  def all_events
    @all_events = @company.events.paginate(:page => params[:page],:per_page => 30)
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:id,:name,:company_type,:url,:tagline,:phone,:number_of_employees,:description,:logo)
    end


end

app/controllers/company/events_controller.rb
class Company::EventsController < ApplicationController

  include Company::EventsHelper

  before_action :set_company
  before_action :set_company_job
  before_action :set_company_event, only: [:show, :edit, :update, :destroy]


  include Company::EventsHelper

  # GET /company/1/events
  # GET /company/1/events.json
  def index
    authorize! :index, @company
    @company_events = @company_job.events.paginate(:page => params[:page],:per_page => 10) 
  end

  # GET /company/1/events/1
  # GET /company/1/events/1.json
  def show
    authorize! :show, @company
  end

  # GET /company/1/events/new
  def new
    authorize! :new, @company
    @company_event = Company::Event.new
  end

  # GET /company/1/events/1/edit
  def edit
    authorize! :edit, @company
  end

  # POST /company/1/events
  # POST /company/1/events.json
  def create
    authorize! :create, @company
    @company_event = @company_job.events.build(company_event_params)

    respond_to do |format|
      if @company_event.save
        flash[:notice] = 'Event was successfully created.'
        format.html { redirect_to company_job_events_path }
        format.json { render :show, status: :created, location: @company_event }
      else
        format.html { render :new }
        format.json { render json: @company_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company/1/events/1
  # PATCH/PUT /company/1/events/1.json
  def update
    authorize! :update, @company
    respond_to do |format|
      if @company_event.update(company_event_params)
        flash[:notice] = 'Event was successfully updated.'
        format.html { redirect_to  company_job_events_path }
        # format.json { render :show, status: :ok, location: @company_event }
      else
        format.html { render :edit }
        format.json { render json: @company_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company/1/events/1
  # DELETE /company/1/events/1.json
  def destroy
    authorize! :destroy, @company
    @company_event.destroy
    flash[:notice] = 'Event was successfully destroyed.'
    respond_to do |format|
      format.html { redirect_to company_job_events_path  }
      format.json { head :no_content }
    end
  end

  private

    def set_company
      @company = Company.find(params[:company_id])
    end

    def set_company_job
      @company_job = Company.find(params[:company_id]).job_opportunities.find(params[:job_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_company_event
      @company_event = @company_job.events.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_event_params
      params.require(:company_event).permit(:event_type,:organiser,:date_time,:duration, :location_attributes => [:building_number,:building_name,:street_address,:street_name,:city,:state,:country,:zipcode])
    end
end

app/controllers/company/job_opportunities_controller.rb
class Company::JobOpportunitiesController < ApplicationController

  load_and_authorize_resource :company
  load_and_authorize_resource :job_opportunity, class: 'Company::JobOpportunity', :through => :company, :param_method => "company_job_opportunity_params"

  #CanCan
  load_resource :skills, through: :job_opportunity
  load_resource :qualifications, through: :job_opportunity
  load_and_authorize_resource

  # callbacks
  # before_action :set_company
  # before_action :set_qualifications
  # before_action :set_skills
  before_action :set_company_job_opportunity, only: [:show, :edit, :update, :select_candidates,:destroy,:send_mail_to_all_shortlisted_candidates,:send_mail_to_shortlisted_candidate]
  before_action :get_candidates, only: [:show, :edit, :update]
  before_action :selected_candidates, only: [:show]
  before_action :get_job_events, only: [:index, :show, :edit]

  # helpers
  include Company::JobOpportunitiesHelper

  # GET /company/job_opportunities
  # GET /company/job_opportunities.json
  def index
    redirect_to home_company_path(@company)
    # @company_job_opportunities = @company.job_opportunities
  end


  # GET /company/job_opportunities/1
  # GET /company/job_opportunities/1.json
  def show
  end

  # GET /company/job_opportunities/new
  def new
    @company_job_opportunity = Company::JobOpportunity.new
  end

  # GET /company/job_opportunities/1/edit
  def edit
  end

  # POST /company/job_opportunities
  # POST /company/job_opportunities.json
  def create
    @company_job_opportunity = @company.job_opportunities.build(company_job_opportunity_params)

    respond_to do |format|
      if @company_job_opportunity.save
        flash[:notice] = 'Job opportunity was successfully created.'
        format.html { redirect_to home_company_path(@company) }
        format.json { render :show, status: :created, location: @company_job_opportunity }
      else
        format.html { render :new }
        format.json { render json: @company_job_opportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company/job_opportunities/1
  # PATCH/PUT /company/job_opportunities/1.json
  def update
    respond_to do |format|
      if @company_job_opportunity.update(company_job_opportunity_params)
        flash[:notice] = 'Job opportunity was successfully updated.'
        format.html { redirect_to  home_company_path(@company) }
        format.json { render :show, status: :ok, location: @company_job_opportunity }
      else
        format.html { render :edit }
        format.json { render json: @company_job_opportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company/job_opportunities/1
  # DELETE /company/job_opportunities/1.json
  def destroy
    @company_job_opportunity.destroy
    flash[:notice] = 'Job opportunity was successfully destroyed.'
    respond_to do |format|
      format.html { redirect_to home_company_path(@company) }
      format.json { head :no_content }
    end
  end

  def select_candidates
    Candidate.find(params[:shortlist][:candidate_ids].reverse.drop(1)).each do |candidate|
      @company_job_opportunity.select_candidate(candidate)
    end
    redirect_to company_job_path(company_id:params[:company_id],id: params[:job_id]) and return
  end

  def send_mail_to_all_shortlisted_candidates
    begin
      @company_job_opportunity.get_candidates_as_users.each do |user|
        UserNotifier.send_shortlist_mail_to(user,@company_job_opportunity).deliver_later
        @company_job_opportunity.change_status(user.info,:mailed)
      end
      flash[:success] = 'Messages sent successfully'
      redirect_to :back
    end
  end

  def send_mail_to_shortlisted_candidate
    begin
      candidate = @company_job_opportunity.candidates.find(params[:candidate_id])
      @company_job_opportunity.change_status(candidate,:mailed)
      UserNotifier.send_shortlist_mail_to(candidate.user,@company_job_opportunity).deliver_later
      flash[:success] = 'Messages sent successfully'
      redirect_to :back
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_company_job_opportunity
      @company_job_opportunity = @company.job_opportunities.find(params[:id]||params[:job_id])
    end

    def set_company
      @company = Company.find(params[:company_id])
    end

    def set_qualifications
      @qualifications = Qualification.all
    end

    def set_skills
      @skills = Skill.all
    end

    def get_candidates
      @shortlisted_candidates = @company_job_opportunity.shortlist_candidates#.paginate(:page => params[:page],:per_page => 10)
    end

    def get_job_events
      @events = @company_job_opportunity.events.paginate(:page => params[:page],:per_page => 1)
    end

    def selected_candidates
      @selected_candidates = @company_job_opportunity.get_candidates_with_status
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_job_opportunity_params
       params.require(:company_job_opportunity).permit(:id, :title, :shift, :description, :number_of_positions, :company_id, :status, :ctc, :experience, qualifications_attributes: [:id, :course, :domain, :_destroy], skills_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company/events_helper.rb
module Company::EventsHelper
	def events_path_params(event_object)
		{ company_id:event_object[:company_id],job_id:event_object[:id] }
	end
	def job_events_path_params(event_object)
		{ company_id:params[:company_id],job_id:params[:job_id],id:event_object.id }
	end
end

app/helpers/company/job_opportunities_helper.rb
module Company::JobOpportunitiesHelper
	def job_opportunity_path_params(job_object)
		{ company_id:job_object.company_id,id:job_object.id }
	end
end

app/views/companies/_form.html.erb
<%= form_for(@company, html: {class: 'form-horizontal', multipart: true }) do |f| %>

<% if @company.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@company.errors.count, "error") %>
    prohibited this company from being saved:</h2>

  <ul>
    <% @company.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field form-group">
  <%= f.label :name, class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :name, class: 'form-control', placeholder: 'Company name', required: 'required' %>
  </div>
</div>

<div class="field form-group">
  <%= f.label :company_type, class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :company_type, class: 'form-control', placeholder: 'MNC, LLC etc', required: 'required' %>
  </div>
</div>

<div class="field form-group">
  <%= f.label :visit_us_at, class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :url, class: 'form-control', placeholder: 'URL of your company', required: 'required' %>
  </div>
</div>

<div class="field form-group">
  <%= f.label :tagline, class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :tagline, class: 'form-control', placeholder: 'Your tagline' %>
  </div>
</div>

<div class="field form-group">
  <%= f.label :phone_number, class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :phone, class: 'form-control', placeholder: 'Phone number', required: 'required' %>
  </div>
</div>

<div class="field form-group">
  <%= f.label :number_of_employees, class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :number_of_employees, class: 'form-control', placeholder: 'Number of Employees' %>
  </div>
</div>

<div class="field form-group">
  <%= f.label :description, class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_area :description, class: 'form-control', placeholder: 'Short but informative description about your company', required: 'required' %>
  </div>
</div>

<div class="field form-group">
  <%= f.label :logo, class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.file_field :logo, class: 'form-control', placeholder: 'Short but informative description about your company', required: 'required' %>
  </div>
</div>

<div class="actions form-group">
  <div class="col-sm-offset-1 col-sm-10">
    <%= f.submit class:"btn btn-default" %>
  </div>
</div>

<% end %>

app/views/companies/all_events.html.erb
<table class="table table-hover text-capitalize">
  <thead>
    <tr>
      <th>Event Type</th>
      <th>Organiser</th>
      <th>Date-Time</th>
      <th>Location-City</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @all_events.each do |event| %>
    <tr>
      <td><%= event.event_type %></td>
      <td><%= event.organiser %></td>
      <td><%= event.date_time.strftime("%b, %d - %Y %I:%M %p") %></td>
      <td><%= event.location.city %></td>
      <td><%#= link_to 'Edit', edit_company_job_event_path(events_path_params( event ) ),class:"btn btn-success", role:"button" %></td>
      <td><%#= link_to 'Destroy', company_job_event_path(events_path_params(event)), method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-danger", role:"button"%></td>
    </tr>
    <% end %>
  </tbody>
  <%= will_paginate @all_events %>
</table>

app/views/companies/edit.html.erb
<h1 class="text-center">Editing Company</h1>

<!-- <%= form_for @company do |f| %> -->
<%= render 'form', :locals => {:f => @company} %>
<!-- <% end %> -->

<!-- <%= link_to 'Show', @company %> -->

app/views/companies/home.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<% @jobs.each do |company_job_opportunity| %>
<div class="well text-capitalize">

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        <b class="text-center">Title</b>
      </div>
      <div class="col-sm-4">
        <%= company_job_opportunity.title %>
      </div>
      <div class="col-sm-5 text-right">
        <%= company_job_opportunity.updated_at.strftime("%b, %d-%Y %I:%M %p") %>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        <b class="text-center">Job Status</b>
      </div>
      <div class="col-sm-9">
        <% if company_job_opportunity.status %>
        Available
      <% else %>
        Closed
        <% end %>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        <b class="text-center">Experience</b>
      </div>
      <div class="col-sm-9">
        <% if company_job_opportunity.experience == 0 %>
        none
      <% else %>
        <%= pluralize(company_job_opportunity.experience, "Year") %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        <b class="text-center">shift</b>
      </div>
      <div class="col-sm-9">
        <%= company_job_opportunity.shift %>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        <b class="text-center">Positions</b>
      </div>
      <div class="col-sm-9">
        <%= company_job_opportunity.number_of_positions %>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        <b class="text-center">CTC</b>
      </div>
      <div class="col-sm-9">
        <%= company_job_opportunity.ctc %>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        <b class="text-center">Description</b>
      </div>
      <div class="col-sm-9">
        <%= company_job_opportunity.description %>
      </div>
    </div>
  </div>

  <div class="field form-group">
    <div class="row">
      <div class="col-sm-12 col-sm-offset-1">

        <%= link_to 'Edit Post', edit_company_job_path(job_opportunity_path_params(company_job_opportunity)),class:"btn btn-warning", role:"button" %>

        <%= link_to 'Remove Post', company_job_path(job_opportunity_path_params(company_job_opportunity)), method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger", role:"button" %>

        <% if company_job_opportunity.events.empty? %>
        <%= link_to 'Create Events', new_company_job_event_path(events_path_params(job_opportunity_path_params(company_job_opportunity))),class:"btn btn-success", role:"button" %>
      <% else %>
        <%= link_to 'Related Events', company_job_events_path(events_path_params(job_opportunity_path_params(company_job_opportunity))),class:"btn btn-success", role:"button" %>
        <% end %>

        <%= link_to 'View Full Post',  company_job_path(job_opportunity_path_params(company_job_opportunity)),class:"btn btn-info", role:"button" %>

      </div>
    </div>
  </div>
  <%= will_paginate @jobs %>
</div>
<% end %>

app/views/companies/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Listing Companies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @companies.each do |company| %>
    <tr>
      <td><%#= link_to 'Show', company %></td>
      <td><%#= link_to 'Edit', edit_company_path(company) %></td>
      <td><%#= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>Create Company Profile</h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
      <b class="text-center">Name</b>
    </div>
    <div class="col-sm-9">
      <p class="text-left"><%= @company.name %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3">
      <b class="text-center">Company Type</b>
    </div>
    <div class="col-sm-9">
      <p class="text-left"><%= @company.company_type %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3">
      <b class="text-center">URL</b>
    </div>
    <div class="col-sm-9">
      <p class="text-left"><%= @company.url %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3">
      <b class="text-center">Tagline</b>
    </div>
    <div class="col-sm-9">
      <p class="text-left"><%= @company.tagline %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3">
      <b class="text-center">Phone</b>
    </div>
    <div class="col-sm-9">
      <p class="text-left"><%= @company.phone %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3">
      <b class="text-center">Description</b>
    </div>
    <div class="col-sm-9">
      <p class="text-left"><%= @company.description %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3">
      <b class="text-center">Number of Employees</b>
    </div>
    <div class="col-sm-9">
      <p class="text-left"><%= @company.number_of_employees %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3">
      <b class="text-center">Company Logo</b>
    </div>
    <div class="col-sm-9">
      <p class="text-left"><%= image_tag( @company.logo , size: "120x70", alt: @company.name) %></p>
    </div>
  </div>




</div>

<div class="col-sm-offset-3">
  <%= link_to 'Edit Profile', edit_company_path(@company), class:"btn btn-default" %>
  <%= link_to 'Job Postings', home_company_path(@company), class:"btn btn-default" %>
</div>