config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root to: "Welcome#index"
  resources :companies do
    member do
      get :home
    end
    member do
      get :all_events
    end
    scope module:'company' do
      resources :jobs, controller: 'job_opportunities' do
        patch :select_candidates
        member do
          post 'select_candidates/mail' => :send_mail_to_all_shortlisted_candidates
          post 'select_candidate/:candidate_id/mail' => :send_mail_to_shortlisted_candidate, as: 'send_mail_to_candidate'
        end
        resources :events, controller: 'events'
      end
    end
  end

  resources :admins

  resources :candidates do
    member do
      get 'home'
      get 'resume'
      get 'jobs'
      scope 'jobs' do
        post ':job_id/apply' => :apply_job, as:'apply_job'
      end
    end
    scope module:'candidate' do
      resources :achievements, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources :projects, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources :course_scores
      resources :experiences, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources  :links, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
      resources :references, except:[:edit,:show,:new] do
        collection do
          get 'edit'
        end
      end
    end
  end

  scope '/candidates/:candidate_id/' do
    resources :qualifications, as:'candidate_qualification', except:[:edit,:show,:new] do
      collection do
        get 'edit'
      end
    end
    resources :skills, as:'candidate_skill', except:[:edit,:show,:new,:update,:create,:destroy] do
      collection do
        get 'edit',as: 'edit'
        put 'update',as: 'update'
      end
    end
    resource :location , as:'candidate_location'
  end

  scope '/companies/:company_id/' do
    resource :location, as:'company_location'
    resources :reviews, as:'company_reviews', only:[:index,:show]
    scope 'jobs/:job_id' do
      resources :qualifications, as:'job_qualification'
      resources :skills, as:'job_skill'
      scope '/events/:event_id' do
        resource :location, as: 'event_location'
      end
    end
  end

end

app/models/candidate/achievement.rb
class Candidate::Achievement
  # concerns
  include Mongoid::Document
  include DatabaseStorageFormat
  
  # callbacks  
  before_save :lower_fields

  # associations 
  belongs_to :candidate

  # validations
	validates :title, length: { maximum: 255 }
	validates :description, length: { maximum: 65535 }
end

app/models/candidate/course_score.rb
class Candidate::CourseScore
include Mongoid::Document
  # concerns
  include DatabaseStorageFormat

  # callbacks
  before_save :lower_fields

  # associations
	belongs_to :qualification
  belongs_to :candidate


  # validations
	validates :end_year, :presence => true
	validates :score, :presence => true 
end

app/models/candidate/experience.rb
class Candidate::Experience
include Mongoid::Document
  # concerns
  include ForbiddenValues
  include DatabaseStorageFormat

  # callbacks
  before_save :lower_fields

  # associations
  belongs_to :candidate

  #validations
  validates :name, :format => REGEX_NAME_FORMAT, length: {maximum: 20},
        :presence => true
  validates :end_date, :presence => true
  validates :description, :length => {maximum: 65535}
  validates :shift_type, :presence => true

  # instance methods


  # class methods
  def self.in_days
    Candidate.joins(:experiences).select('SUM(DATEDIFF(candidate_experiences.end_date,candidate_experiences.start_date)) AS days,candidates.*').group(:candidate_id).order('1 DESC')
  end

end

app/models/candidate/link.rb
class Candidate::Link
include Mongoid::Document
  # concerns
	include DatabaseStorageFormat

  # callbacks
  before_save :lower_fields

  # associations
	belongs_to :candidate

	validates :link_type, :presence => true, :length => { maximum: 50 }
	validates :url, :presence => true, :length => { maximum: 65535 }
end

app/models/candidate/test_score.rb
class Candidate::TestScore
include Mongoid::Document
  # concerns
  include ForbiddenValues
  include DatabaseStorageFormat

  # callbacks
  before_save :lower_fields

  # associations
  belongs_to :candidate
  belongs_to :test

  # validations
  validates :score, presence:true
  validate :valid_score?
end

app/controllers/candidate/achievements_controller.rb
class Candidate::AchievementsController < ApplicationController

  load_and_authorize_resource :candidate
  load_and_authorize_resource :achievement, :through => :candidate, :param_method  => :candidate_achievement_params

  # layouts 
  layout 'candidate/layout'

  # helpers
  include Candidate::AchievementsHelper

  # filters/callbacks
  before_action :set_candidate
  before_action :set_candidate_achievement, only: [:show, :update, :destroy]
    

  # GET /candidate/:id/achievements
  # GET /candidate/:id/achievements.json
  def index
    @candidate_achievements = @candidate.achievements
  end


  # GET /candidate/:id/achievements/edit
  def edit
    @candidate_achievements = @candidate.achievements
    @new_candidate_achievement = Candidate::Achievement.new
  end

  # POST /candidate/:id/achievements
  # POST /candidate/:id/achievements.json
  def create
    @candidate_achievement  = @candidate.achievements.build(candidate_achievement_params)

    respond_to do |format|
      if @candidate_achievement.save
        flash[:success] =  'Achievement was successfully created.' 
        format.html { redirect_to edit_candidate_achievements_path(params[:candidate_id])}
        format.json { render :show, status: :created, location: @candidate_achievement }
      else
        flash[:failure] = 'Achievement creation  unsuccessful'
        format.html { redirect_to edit_candidate_achievements_path(params[:candidate_id])}
        format.json { render json: @candidate_achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidate/:id/achievements/1
  # PATCH/PUT /candidate/:id/achievements/1.json
  def update
    respond_to do |format|
      if @candidate_achievement.update(candidate_achievement_params)
        flash[:success] =  'Achievement was successfully updated.' 
        format.html { redirect_to edit_candidate_achievements_path(params[:candidate_id]) }
        format.json { render :show, status: :ok, location: @candidate_achievement }
      else
        flash[:failure] = 'Achievement updation unsuccessful'
        @candidate_achievements = [@candidate_achievement]
        @new_candidate_achievement = Candidate::Achievement.new
        format.html { redirect edit_candidate_achievements_path(params[:candidate_id]) }
        format.json { render json: @candidate_achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidate/:id/achievements/1
  # DELETE /candidate/:id/achievements/1.json
  def destroy
    @candidate_achievement.destroy
    respond_to do |format|
      flash[:success] =  'Achievement was successfully deleted.' 
      format.html { redirect_to edit_candidate_achievements_path(params[:candidate_id]) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:candidate_id])
    end

    def set_candidate_achievement
      @candidate_achievement = @candidate.achievements.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_achievement_params
      params.require(:candidate_achievement).permit(:title,:description)
    end
end

app/controllers/candidate/course_scores_controller.rb
class Candidate::CourseScoresController < CandidatesController

  include Candidate::CourseScoresHelper

  before_action :set_candidate
  before_action :set_candidate_course_score,only: [:show, :edit, :update, :destroy]


  before_action :get_qualifications, only: [:edit, :update, :create, :new]

  # GET /candidate/course_scores
  # GET /candidate/course_scores.json
  def index
    @candidate_course_scores = @candidate.course_scores
  end

  # GET /candidate/course_scores/1
  # GET /candidate/course_scores/1.json
  def show
  end

  # GET /candidate/course_scores/new
  def new
    @candidate_course_score = Candidate::CourseScore.new
  end

  # GET /candidate/course_scores/1/edit
  def edit
  end

  # POST /candidate/course_scores
  # POST /candidate/course_scores.json
  def create
    @candidate_course_score = @candidate.course_scores.build(candidate_course_score_params)

    respond_to do |format|
      if @candidate_course_score.save
        flash[:notice] = 'Course score was successfully created.'
        format.html { redirect_to candidate_course_score_path(course_score_path_params(@candidate_course_score)) }
        format.json { render :show, status: :created, location: @candidate_course_score }
      else
        format.html { render :new }
        format.json { render json: @candidate_course_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidate/course_scores/1
  # PATCH/PUT /candidate/course_scores/1.json
  def update
    respond_to do |format|
      if @candidate_course_score.update(candidate_course_score_params)
        flash[:notice] = 'Course score was successfully updated.'
        format.html { redirect_to candidate_course_score_path(course_score_path_params(@candidate_course_score)) }
        format.json { render :show, status: :ok, location: @candidate_course_score }
      else
        format.html { render :edit }
        format.json { render json: @candidate_course_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidate/course_scores/1
  # DELETE /candidate/course_scores/1.json
  def destroy
    @candidate_course_score.destroy
    flash[:notice] = 'Course score was successfully destroyed.'
    respond_to do |format|
      format.html { redirect_to candidate_course_scores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:candidate_id])
    end

    def set_candidate_course_score
      @candidate_course_score = @candidate.course_scores.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_course_score_params
      params.require(:candidate_course_score).permit(:start_year,:end_year,:score,:qualification_id)
    end

    # get all the availbale qualifications
    def get_qualifications
      @qualifications  = Qualification.all
    end
end

app/controllers/candidate/experiences_controller.rb
class Candidate::ExperiencesController < ApplicationController

  load_and_authorize_resource :candidate
  load_and_authorize_resource :experience, :through => :candidate, :param_method => :candidate_experience_params
  #layout 
  layout 'candidate/layout'
  # helpers
  include Candidate::ExperiencesHelper

  # filters/callbacks
  before_action :set_candidate
  before_action :set_candidate_experience, only: [:show,:update, :destroy]

  # GET /candidate/:id/experiencess
  # GET /candidate/:id/experiencess.json
  def index
    @candidate_experiences = @candidate.experiences
  end


  # GET /candidate/:id/experiencess/1/edit
  def edit
    @candidate_experiences = @candidate.experiences
    @new_candidate_experience = Candidate::Experience.new
  end

  # POST /candidate/:id/experiencess
  # POST /candidate/:id/experiencess.json
  def create
    @candidate_experience = @candidate.experiences.build(candidate_experience_params)

    respond_to do |format|
      if @candidate_experience.save
        flash[:success] =  'Experience was successfully created.'
        format.html { redirect_to edit_candidate_experiences_path(params[:candidate_id]) }
        format.json { render :show, status: :created, location: @candidate_experience }
      else
        flash[:failure] =  'Experience creation unsuccessful.'
        format.html { redirect_to edit_candidate_experiences_path(params[:candidate_id]) }
        format.json { render json: @candidate_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidate/:id/experiencess/1
  # PATCH/PUT /candidate/:id/experiencess/1.json
  def update
    respond_to do |format|
      if @candidate_experience.update(candidate_experience_params)
        flash[:success] =  'Experience was successfully updated.'
        format.html { redirect_to edit_candidate_experiences_path(params[:candidate_id])}
        format.json { render :show, status: :ok, location: @candidate_experience }
      else
        flash[:failure] =  'Experience updation unsuccessful.'
        @new_candidate_experience = Candidate::Experience.new
        @candidate_experiences = [@candidate_experience]
        format.html { redirect_to edit_candidate_experiences_path(params[:candidate_id]) }
        format.json { render json: @candidate_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidate/:id/experiencess/1
  # DELETE /candidate/:id/experiencess/1.json
  def destroy
    @candidate_experience.destroy
    flash[:success] =  'Experience was successfully deleted'
    respond_to do |format|
      format.html { redirect_to edit_candidate_experiences_path}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_candidate
      @candidate = Candidate.find(params[:candidate_id])
    end

    def set_candidate_experience
      @candidate_experience = @candidate.experiences.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_experience_params
      params.require(:candidate_experience).permit(:name,:start_date,:end_date,:description,:shift_type)
    end
end

app/controllers/candidate/links_controller.rb
class Candidate::LinksController < ApplicationController

  load_and_authorize_resource :candidate
  load_and_authorize_resource :links,:through => :candidate, :param_method => :candidate_links_params
  layout 'candidate/layout'
  # helpers
  include Candidate::LinksHelper

  # filters/callbacks
  before_action :set_candidate
  before_action :set_candidate_link, only: [:show, :update, :destroy]

  # GET /candidate/:id/links
  # GET /candidate/:id/links.json
  def index
    @candidate_links = @candidate.links
  end


  # GET /candidate/:id/links/edit
  def edit
    @candidate_links = @candidate.links
    @new_candidate_link = Candidate::Link.new
  end


  # POST /candidate/:id/links
  # POST /candidate/:id/links.json
  def create
    @candidate_link = @candidate.links.build(candidate_link_params)

    respond_to do |format|
      if @candidate_link.save
        flash[:success] =  'Link was successfully created.' 
        format.html { redirect_to edit_candidate_links_path(params[:candidate_id])}
        format.json { render :show, status: :created, location: @candidate_link }
      else
        flash[:failure] =  'Link creation unsuccessful.' 
        format.html { redirect_to  edit_candidate_links_path(params[:candidate_id]) }
        format.json { render json: @candidate_link.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /candidate/:id/links/1
  # PATCH/PUT /candidate/:id/links/1.json
  def update
    respond_to do |format|
      if @candidate_link.update(candidate_link_params)
        flash[:success] =  'Link was successfully updated.' 
        format.html { redirect_to edit_candidate_links_path(params[:candidate_id])}
        format.json { render :show, status: :ok, location: @candidate_link }
      else
        flash[:failure] =  'Link updation unsuccessful.' 
        format.html { redirect_to edit_candidate_links_path(params[:candidate_id]) }
        format.json { render json: @candidate_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidate/:id/links/1
  # DELETE /candidate/:id/links/1.json
  def destroy
    @candidate_link.destroy
    flash[:notice] = 'Link was successfully destroyed.' 
    respond_to do |format|
      flash[:success] =  'Link was successfully deleted.' 
      format.html { redirect_to edit_candidate_links_path(params[:candidate_id])}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:candidate_id])
    end

    def set_candidate_link
      @candidate_link = @candidate.links.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_link_params
      params.require(:candidate_link).permit(:url,:link_type)
    end
end

app/helpers/candidate/achievements_helper.rb
module Candidate::AchievementsHelper

  def achievement_path_params(achievement)
    {candidate_id:params[:candidate_id],id: achievement.id}
  end

end

app/helpers/candidate/course_scores_helper.rb
module Candidate::CourseScoresHelper
  def course_score_path_params(course_score)
    { candidate_id:params[:candidate_id], id:course_score.id }
  end
end

app/helpers/candidate/experiences_helper.rb
module Candidate::ExperiencesHelper

  def experience_path_params(experience)
    {candidate_id:params[:candidate_id],id: experience}
  end

end

app/helpers/candidate/links_helper.rb
module Candidate::LinksHelper
  def link_path_params(link)
    {candidate_id: params[:candidate_id],id: link.id}
  end
end

app/views/candidate/projects/_form.html.erb
<div class="row well">
  <div class="col-sm-9">

    <%= form_for(candidate_project, url: required_url) do |f| %>
      <% if candidate_project.errors.any? %>
        <div class="alert alert-danger">
          <div id="error_explanation">
            <h3><%= pluralize(candidate_project.errors.count, "error") %> prohibited this candidate_project from being saved:</h3>

            <ul>
              <% candidate_project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <%  end %>
            </ul>
          </div>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label(:title, class: "control-label col-sm-3")  %>
        <div class="col-sm-9">
          <%= f.text_field(:title, class: "form-control",placeholder:"Enter title") %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label(:domain, class: "control-label col-sm-3")  %>
        <div class="col-sm-9">
          <%= f.text_field(:domain, class: "form-control",placeholder:"Enter domain of project") %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label(:description, class: "control-label col-sm-3")  %>
        <div class="col-sm-9">
          <%= f.text_area(:description, class: "form-control",placeholder:"Write description of the project",rows:5) %>

        </div>
      </div>
      <div class="form-group">
        <%= f.label(:start_date, class: "control-label col-sm-3")  %>
        <div class="col-sm-9">
          <%= f.date_field(:start_date, class: "form-control",placeholder:"Enter start date of prject") %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label(:end_date, class: "control-label col-sm-3")  %>
        <div class="col-sm-9">
          <%= f.date_field(:end_date, class: "form-control",placeholder:"Enter end date of project") %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label(:position, class: "control-label col-sm-3")  %>
        <div class="col-sm-9">
          <%= f.text_field(:position, class: "form-control",placeholder:"What was your role in this") %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label(:organisation, class: "control-label col-sm-3")  %>
        <div class="col-sm-9">
          <%= f.text_field(:organisation, class: "form-control",placeholder:"For which organization was this for") %>
        </div>
      </div>
  </div>

  <div class="form-group">
    <% if !new_project %>
      <div class="col-sm-2">
        <%= f.submit "Update",class: "btn btn-default update-button btn-md" %>
      </div>
    <% else %>
      <div class="col-sm-offset-2 create-button">
        <%= f.submit "Create",class:"btn btn-default" %>
      </div>
    <% end %>
  </div>

<% end %>
<% if !new_project %>
  <div class="form-group">
    <div class="col-sm-1">
      <%= link_to "Delete",candidate_project_path(project_path_params(candidate_project)),method: :delete,data:{confirm: 'Are you sure?'} ,class:"btn btn-danger btn-md active", role:"button" %>

    </div>
  </div>
 
<% end %>
</div>

app/views/candidate/projects/edit.html.erb
<% content_for :edit_content do %>

  <div class="row project-title">
    <h2 class="col-sm-5">Projects</h2>
    <button class="btn btn-default col-sm-1 add-button-project" data-toggle="modal" data-target="#myModal">Add</button>
  </div>
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add project</h4>
        </div>
        <div class="modal-body">
          <%= render partial: 'form', locals:{candidate_project: @new_candidate_project,required_url:candidate_projects_path,new_project: true} %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
  <% @candidate_projects.each do |candidate_project| %>
    <%= render partial: 'form', locals:{candidate_project: candidate_project, required_url: candidate_project_path(project_path_params(candidate_project)), new_project: false}%>
  <% end %>
<% end  %>

<%= render 'candidates/edit_navbar' %>

app/views/candidate/projects/index.html.erb
<% content_for :show_content do %>
  <h2>Projects</h2>
  <% @candidate_projects.each do |candidate_project| %>
    <div class="well">
      <div class="row">
        <div class="col-sm-3">
          <p><b>Title</b></p>
        </div>
        <div class="col-sm-6">
          <p><%= candidate_project.title %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <p><b>Domain</b></p>
        </div>
        <div class="col-sm-6">
          <p><%= candidate_project.domain %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <p><b>Start date</b></p>
        </div>
        <div class="col-sm-6">
          <p><%= candidate_project.start_date %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <p><b>End date</b></p>
        </div>
        <div class="col-sm-6">
          <p><%= candidate_project.end_date %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <p><b>Position</b></p>
        </div>
        <div class="col-sm-6">
          <p><%= candidate_project.position %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <p><b>Organisation</b></p>
        </div>
        <div class="col-sm-6">
          <p><%= candidate_project.organisation%></p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <p><b>Description</b></p>
        </div>
        <div class="col-sm-6">
          <p><%= candidate_project.description %></p>
        </div>
      </div>
    </div>
  <% end %>
  <%= link_to "Edit Projects", edit_candidate_projects_path(params[:id]||params[:candidate_id]),class:"btn btn-default text-center",onclick: "javascript:window.location.reload()" %>
<%  end %>

<%= render "candidates/show_navbar" %>